import palletTownImage from "../assets/map/pallet-town.png";
import { MapId, MapType } from "./map-types";

import music from "../assets/music/maps/pallet-town.mp3";

const palletTown: MapType = {
  name: "Pallet Town",
  image: palletTownImage,
  height: 18,
  width: 20,
  start: {
    x: 8,
    y: 13,
  },
  walls: {
    0: {
      9: true,
      12: true,
    },
    1: {
      0: true,
      1: true,
      2: true,
      3: true,
      4: true,
      5: true,
      6: true,
      7: true,
      8: true,
      9: true,
      12: true,
      13: true,
      14: true,
      15: true,
      16: true,
      17: true,
      18: true,
      19: true,
    },
    2: {
      0: true,
      19: true,
    },
    3: {
      0: true,
      4: true,
      5: true,
      6: true,
      7: true,
      12: true,
      13: true,
      14: true,
      15: true,
      19: true,
    },
    4: {
      0: true,
      4: true,
      5: true,
      6: true,
      7: true,
      12: true,
      13: true,
      14: true,
      15: true,
      19: true,
    },
    5: {
      0: true,
      3: true,
      4: true,
      6: true,
      7: true,
      11: true,
      12: true,
      14: true,
      15: true,
      19: true,
    },
    6: {
      0: true,
      19: true,
    },
    7: {
      0: true,
      19: true,
    },
    8: {
      0: true,
      4: true,
      10: true,
      11: true,
      12: true,
      13: true,
      14: true,
      15: true,
      19: true,
    },
    9: {
      0: true,
      4: true,
      5: true,
      6: true,
      7: true,
      10: true,
      11: true,
      12: true,
      13: true,
      14: true,
      15: true,
      19: true,
    },
    10: {
      0: true,
      10: true,
      11: true,
      12: true,
      13: true,
      14: true,
      15: true,
      19: true,
    },
    11: {
      0: true,
      10: true,
      11: true,
      13: true,
      14: true,
      15: true,
      19: true,
    },
    12: {
      0: true,
      19: true,
    },
    13: {
      0: true,
      10: true,
      11: true,
      12: true,
      13: true,
      14: true,
      15: true,
      19: true,
    },
    14: {
      0: true,
      4: true,
      5: true,
      6: true,
      7: true,
      19: true,
    },
    15: {
      0: true,
      4: true,
      5: true,
      6: true,
      7: true,
      10: true,
      19: true,
    },
    16: {
      0: true,
      4: true,
      5: true,
      6: true,
      7: true,
      19: true,
    },
    17: {
      0: true,
      1: true,
      4: true,
      5: true,
      6: true,
      7: true,
      8: true,
      9: true,
      10: true,
      11: true,
      12: true,
      13: true,
      14: true,
      15: true,
      16: true,
      17: true,
      18: true,
      19: true,
    },
    18: {
      2: true,
      3: true,
    },
  },
  text: {
    5: {
      3: [
        "Lorem ipsum dolor sit amet, consectetur",
        "adipiscing elit, sed do eiusmod tempor",
        "incididunt ut labore et dolore magna aliqua.",
      ],
      11: [
        "Lorem ipsum dolor sit amet, consectetur",
        "adipiscing elit, sed do eiusmod tempor",
        "incididunt ut labore et dolore magna aliqua.",
      ],
    },
    8: {
      4: [
        "Lorem ipsum dolor sit amet, consectetur",
        "adipiscing elit, sed do eiusmod tempor",
        "incididunt ut labore et dolore magna aliqua.",
      ],
    },
    9: {
      7: [
        "Lorem ipsum dolor sit amet, consectetur",
        "adipiscing elit, sed do eiusmod tempor",
        "incididunt ut labore et dolore magna aliqua.",
      ],
    },
    13: {
      13: [
        "Lorem ipsum dolor sit amet, consectetur",
        "adipiscing elit, sed do eiusmod tempor",
        "incididunt ut labore et dolore magna aliqua.",
      ],
    },
    15: {
      10: [
        "Lorem ipsum dolor sit amet, consectetur",
        "adipiscing elit, sed do eiusmod tempor",
        "incididunt ut labore et dolore magna aliqua.",
      ],
    },
  },
  maps: {
    5: {
      5: MapId.PalletTownHouseA1F,
      13: MapId.PalletTownHouseB,
    },
    11: {
      12: MapId.PalletTownLab,
    },
    0: {
      10: MapId.Route1,
      11: MapId.Route1,
    },
  },
  exits: {},
  music,
  encounters: {
    walk: { rate: 0, pokemon: [] },
    oldRod: {
      rate: 10,
      pokemon: [
        {
          id: 129,
          chance: 100,
          conditionValues: [],
          maxLevel: 5,
          minLevel: 5,
        },
      ],
    },
    goodRod: {
      rate: 10,
      pokemon: [
        {
          id: 60,
          chance: 50,
          conditionValues: [],
          maxLevel: 10,
          minLevel: 10,
        },
        {
          id: 118,
          chance: 50,
          conditionValues: [],
          maxLevel: 10,
          minLevel: 10,
        },
      ],
    },
    superRod: {
      rate: 10,
      pokemon: [
        {
          id: 60,
          chance: 17,
          conditionValues: [],
          maxLevel: 15,
          minLevel: 15,
        },
        {
          id: 60,
          chance: 8,
          conditionValues: [],
          maxLevel: 15,
          minLevel: 15,
        },
        {
          id: 60,
          chance: 25,
          conditionValues: [],
          maxLevel: 15,
          minLevel: 15,
        },
        {
          id: 72,
          chance: 25,
          conditionValues: [],
          maxLevel: 15,
          minLevel: 15,
        },
        {
          id: 72,
          chance: 8,
          conditionValues: [],
          maxLevel: 15,
          minLevel: 15,
        },
        {
          id: 72,
          chance: 17,
          conditionValues: [],
          maxLevel: 15,
          minLevel: 15,
        },
      ],
    },
    surf: { rate: 1, pokemon: [] },
    rockSmash: { rate: 0, pokemon: [] },
    headbutt: { rate: 0, pokemon: [] },
    darkGrass: { rate: 0, pokemon: [] },
    grassSpots: { rate: 0, pokemon: [] },
    caveSpots: { rate: 0, pokemon: [] },
    bridgeSpots: { rate: 0, pokemon: [] },
    superRodSpots: { rate: 0, pokemon: [] },
    surfSpots: { rate: 0, pokemon: [] },
    yellowFlowers: { rate: 0, pokemon: [] },
    purpleFlowers: { rate: 0, pokemon: [] },
    redFlowers: { rate: 0, pokemon: [] },
    roughTerrain: { rate: 0, pokemon: [] },
    gift: {
      rate: 0,
      pokemon: [
        {
          id: 1,
          chance: 100,
          conditionValues: [],
          maxLevel: 5,
          minLevel: 5,
        },
        {
          id: 4,
          chance: 100,
          conditionValues: [],
          maxLevel: 5,
          minLevel: 5,
        },
        {
          id: 7,
          chance: 100,
          conditionValues: [],
          maxLevel: 5,
          minLevel: 5,
        },
      ],
    },
    giftEgg: { rate: 0, pokemon: [] },
    onlyOne: { rate: 0, pokemon: [] },
  },
  grass: {},
  recoverLocation: { x: 5, y: 6 },
};

export default palletTown;
